"""
Test Python KPP implementation against real MITgcm validation captures.

Rewritten for 1DMIX-011: the previous version of this file expected a
`.npz` fixture format that was never generated by any script in this repo
(its own docstring referenced a nonexistent `parse_mitgcm_kpp_validation.py`),
used a stale `sys.path` from before the 2026-09-18 repo reorganization, called
`KPPDriver.compute_mixing` with a keyword (`f_coriolis`) that never existed in
its real signature (`coriol`), and never actually configured lab_sea-specific
parameters despite its docstring claiming to. It could never have run.

This version drives the project's actual, proven replay pipeline
(`scripts/run_kpp_from_netcdf_input.py::run_python_kpp_on_dataset`, the same
function used for every KPP validation capture in this project) against
already-captured NetCDF data for two experiments:
- 1D_ocean_ice_column (single column, 10 timesteps, no land, full-depth)
- lab_sea (20x16 grid, subsampled to the first 20 of 999 timesteps for test
  speed; land columns and per-column bathymetry are handled by the pipeline
  itself, see closed issue 1DMIX-018)

Tolerances are set from the real, measured agreement levels recorded in
closed_issues.md / open_issues.md (1DMIX-013, 1DMIX-018, 1DMIX-019), not
aspirational bit-level values that were never actually achieved for a
multi-column case.
"""

import sys
from pathlib import Path

import numpy as np
import pytest
import xarray as xr

_VERIFICATION_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_VERIFICATION_ROOT / 'scripts'))
sys.path.insert(0, str(_VERIFICATION_ROOT.parent / 'Vertical_Mixing_Models'))

from run_kpp_from_netcdf_input import run_python_kpp_on_dataset  # noqa: E402

DATA_1D = (_VERIFICATION_ROOT / 'KPP_port_validation' / 'inputs_from_mitgcm'
           / 'mitgcm_kpp_inputs_1D_10_kppmix_extend_rawflux_fix.nc')
OUTPUTS_1D = (_VERIFICATION_ROOT / 'KPP_port_validation' / 'outputs_from_mitgcm'
              / 'mitgcm_kpp_outputs_1D_10_kppmix_extend_rawflux_fix.nc')
DATA_LABSEA = (_VERIFICATION_ROOT / 'KPP_port_validation' / 'inputs_from_mitgcm'
               / 'mitgcm_kpp_inputs_lab_sea_1000_0820T0946.nc')
OUTPUTS_LABSEA = (_VERIFICATION_ROOT / 'KPP_port_validation' / 'outputs_from_mitgcm'
                  / 'mitgcm_kpp_outputs_lab_sea_1000_0820T0946.nc')


def _require(path: Path) -> None:
    if not path.exists():
        pytest.skip(f"Required MITgcm capture not found: {path}")


# ========================================================================
# 1D_ocean_ice_column: single column, no land, full-depth every level
# ========================================================================

@pytest.fixture(scope='module')
def result_1d():
    _require(DATA_1D)
    _require(OUTPUTS_1D)
    inputs_ds = xr.open_dataset(DATA_1D)
    python_ds = run_python_kpp_on_dataset(inputs_ds, verbose=False)
    mitgcm_ds = xr.open_dataset(OUTPUTS_1D)
    return python_ds, mitgcm_ds


def test_1d_ocean_ice_column_hbl(result_1d):
    python_ds, mitgcm_ds = result_1d
    nt = python_ds.sizes['time']
    diff = np.abs(python_ds['hbl'].values - mitgcm_ds['hbl'].values[:nt])
    assert np.max(diff) < 0.02, f"max hbl diff {np.max(diff):.4f} m exceeds 0.02 m"


def test_1d_ocean_ice_column_visc_az(result_1d):
    python_ds, mitgcm_ds = result_1d
    nt = python_ds.sizes['time']
    mitgcm_visc = mitgcm_ds['visc_az'].values[:nt]
    python_visc = python_ds['visc_az'].values
    active = mitgcm_visc > 1e-6
    rel_err = np.abs(python_visc[active] - mitgcm_visc[active]) / mitgcm_visc[active]
    assert np.median(rel_err) < 0.001, f"median visc_az rel err {np.median(rel_err):.4%} regressed"
    assert np.max(rel_err) < 0.02, f"max visc_az rel err {np.max(rel_err):.4%} regressed"


# ========================================================================
# lab_sea: 20x16 grid, real land columns and variable per-column bathymetry
# ========================================================================

@pytest.fixture(scope='module')
def result_labsea():
    _require(DATA_LABSEA)
    _require(OUTPUTS_LABSEA)
    inputs_ds = xr.open_dataset(DATA_LABSEA)
    # The full 999-timestep x 320-column grid takes several minutes; a
    # 20-timestep subsample is enough for a regression test. The full run's
    # results are the recorded evidence in closed issue 1DMIX-018 / open
    # issue 1DMIX-019, not reproduced here on every test invocation.
    python_ds = run_python_kpp_on_dataset(inputs_ds, verbose=False,
                                           first_timestep=0, last_timestep=19)
    mitgcm_ds = xr.open_dataset(OUTPUTS_LABSEA)
    return inputs_ds, python_ds, mitgcm_ds


def _ocean_mask(inputs_ds: xr.Dataset, n_time: int) -> np.ndarray:
    theta = inputs_ds['temperature'].values[:n_time]
    salt = inputs_ds['salinity'].values[:n_time]
    is_land = np.all(theta == 0.0, axis=-1) & np.all(salt == 0.0, axis=-1)
    return ~is_land


def test_lab_sea_hbl_ocean_columns(result_labsea):
    inputs_ds, python_ds, mitgcm_ds = result_labsea
    nt = python_ds.sizes['time']
    ocean = _ocean_mask(inputs_ds, nt)
    diff = np.abs(python_ds['hbl'].values - mitgcm_ds['hbl'].values[:nt])
    diff_ocean = diff[ocean]
    # See open issue 1DMIX-019: a small long tail of columns disagrees due to
    # bulk-Richardson threshold-crossing sensitivity (Rib landing within a
    # fraction of a percent of Ricr), not a systematic port defect. These
    # bounds reflect the full 999-timestep run's measured distribution
    # (median 0.004 m, 0.25% of columns exceed 5 m) with headroom for this
    # test's smaller 20-timestep sample.
    assert np.median(diff_ocean) < 0.5, f"median hbl diff {np.median(diff_ocean):.4f} m regressed"
    assert np.mean(diff_ocean > 5.0) < 0.02, "fraction of columns exceeding the known 1DMIX-019 tail grew"


def test_lab_sea_visc_az_median(result_labsea):
    inputs_ds, python_ds, mitgcm_ds = result_labsea
    nt = python_ds.sizes['time']
    mitgcm_visc = mitgcm_ds['visc_az'].values[:nt]
    python_visc = python_ds['visc_az'].values
    active = mitgcm_visc > 1e-6
    abs_err = np.abs(python_visc[active] - mitgcm_visc[active])
    # Full run's measured median is exactly 0.0; allow headroom for sampling.
    assert np.median(abs_err) < 1e-5, f"median visc_az abs err {np.median(abs_err):.2e} regressed"
    assert np.percentile(abs_err, 99) < 0.01, f"p99 visc_az abs err {np.percentile(abs_err, 99):.2e} regressed"
