"""
Test Python KPP implementation against real MITgcm validation captures.

Rewritten for 1DMIX-011: the previous version of this file expected a
`.npz` fixture format that was never generated by any script in this repo
(its own docstring referenced a nonexistent `parse_mitgcm_kpp_validation.py`),
used a stale `sys.path` from before the 2026-09-18 repo reorganization, called
`KPPDriver.compute_mixing` with a keyword (`f_coriolis`) that never existed in
its real signature (`coriol`), and never actually configured lab_sea-specific
parameters despite its docstring claiming to. It could never have run.

This version drives the project's actual, proven replay pipeline
(`scripts/run_kpp_from_netcdf_input.py::run_python_kpp_on_dataset`, the same
function used for every KPP validation capture in this project) against
already-captured NetCDF data for two experiments:
- 1D_ocean_ice_column (single column, 10 timesteps, no land, full-depth)
- lab_sea (20x16 grid, subsampled to the first 20 of 999 timesteps for test
  speed; land columns and per-column bathymetry are handled by the pipeline
  itself, see closed issue 1DMIX-018)

Tolerances are set from the real, measured agreement levels recorded in
closed_issues.md / open_issues.md (1DMIX-013, 1DMIX-018, 1DMIX-019), not
aspirational bit-level values that were never actually achieved for a
multi-column case. Since 1DMIX-071 the replay feeds the port MITgcm's tracer-point
`shsq`/`dVsq`/smoothed `dbloc` (rebuilt from the neighbouring captured columns), and the multi-column
`lab_sea` bounds below were re-measured and tightened on that basis: the `hbl` tail that 1DMIX-019
attributed to Rib/Ricr threshold sensitivity was largely a replay-input effect (see the comments in the
`lab_sea` tests and `KPP_port_validation/KPP_VALIDATION_RESULTS.md`). Since 1DMIX-080 the port uses MITgcm's
hard-coded Jerlov water type IA (`swfrac.F` line 92) instead of IB; the remaining `lab_sea` differences were that,
and both experiments' bounds were tightened again (figures in the tests).
"""

import sys
from pathlib import Path

import numpy as np
import pytest
import xarray as xr

_VERIFICATION_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_VERIFICATION_ROOT / 'scripts'))
sys.path.insert(0, str(_VERIFICATION_ROOT.parent / 'Vertical_Mixing_Models'))

from run_kpp_from_netcdf_input import run_python_kpp_on_dataset  # noqa: E402

DATA_1D = (_VERIFICATION_ROOT / 'KPP_port_validation' / 'inputs_from_mitgcm'
           / 'mitgcm_kpp_inputs_1D_10_kppmix_extend_rawflux_fix.nc')
OUTPUTS_1D = (_VERIFICATION_ROOT / 'KPP_port_validation' / 'outputs_from_mitgcm'
              / 'mitgcm_kpp_outputs_1D_10_kppmix_extend_rawflux_fix.nc')
DATA_LABSEA = (_VERIFICATION_ROOT / 'KPP_port_validation' / 'inputs_from_mitgcm'
               / 'mitgcm_kpp_inputs_lab_sea_1000_0820T0946.nc')
OUTPUTS_LABSEA = (_VERIFICATION_ROOT / 'KPP_port_validation' / 'outputs_from_mitgcm'
                  / 'mitgcm_kpp_outputs_lab_sea_1000_0820T0946.nc')


def _require(path: Path) -> None:
    if not path.exists():
        pytest.skip(f"Required MITgcm capture not found: {path}")


# ========================================================================
# 1D_ocean_ice_column: single column, no land, full-depth every level
# ========================================================================

@pytest.fixture(scope='module')
def result_1d():
    _require(DATA_1D)
    _require(OUTPUTS_1D)
    inputs_ds = xr.open_dataset(DATA_1D)
    python_ds = run_python_kpp_on_dataset(inputs_ds, verbose=False)
    mitgcm_ds = xr.open_dataset(OUTPUTS_1D)
    return python_ds, mitgcm_ds


def test_1d_ocean_ice_column_hbl(result_1d):
    python_ds, mitgcm_ds = result_1d
    nt = python_ds.sizes['time']
    diff = np.abs(python_ds['hbl'].values - mitgcm_ds['hbl'].values[:nt])
    # 1DMIX-080 (2026-10-03): with MITgcm's hard-coded Jerlov type IA (swfrac.F line 92) instead of IB, max
    # 0.0129 -> 1.38e-3 m. Bound tightened 0.02 -> 0.005 (the lab_sea hbl convention below). The remainder is
    # this capture's KPPuseSWfrac3D = 1 branch (MITgcm interpolates SWFrac3D), which the port does not implement.
    assert np.max(diff) < 0.005, f"max hbl diff {np.max(diff):.4f} m exceeds 0.005 m"


def test_1d_ocean_ice_column_visc_az(result_1d):
    python_ds, mitgcm_ds = result_1d
    nt = python_ds.sizes['time']
    mitgcm_visc = mitgcm_ds['visc_az'].values[:nt]
    python_visc = python_ds['visc_az'].values
    active = mitgcm_visc > 1e-6
    rel_err = np.abs(python_visc[active] - mitgcm_visc[active]) / mitgcm_visc[active]
    assert np.median(rel_err) < 0.001, f"median visc_az rel err {np.median(rel_err):.4%} regressed"
    # 1DMIX-080 (2026-10-03, Jerlov type IA): max rel err 4.8e-3 -> 4.5e-4; bound tightened 0.02 -> 0.001
    # (this test's median convention).
    assert np.max(rel_err) < 0.001, f"max visc_az rel err {np.max(rel_err):.4%} regressed"


# ========================================================================
# lab_sea: 20x16 grid, real land columns and variable per-column bathymetry
# ========================================================================

@pytest.fixture(scope='module')
def result_labsea():
    _require(DATA_LABSEA)
    _require(OUTPUTS_LABSEA)
    inputs_ds = xr.open_dataset(DATA_LABSEA)
    # The full 999-timestep x 320-column grid takes several minutes; a
    # 20-timestep subsample is enough for a regression test. The full run's
    # results are the recorded evidence in closed issue 1DMIX-018 / open
    # issue 1DMIX-019, not reproduced here on every test invocation.
    python_ds = run_python_kpp_on_dataset(inputs_ds, verbose=False,
                                           first_timestep=0, last_timestep=19)
    mitgcm_ds = xr.open_dataset(OUTPUTS_LABSEA)
    return inputs_ds, python_ds, mitgcm_ds


def _ocean_mask(inputs_ds: xr.Dataset, n_time: int) -> np.ndarray:
    theta = inputs_ds['temperature'].values[:n_time]
    salt = inputs_ds['salinity'].values[:n_time]
    is_land = np.all(theta == 0.0, axis=-1) & np.all(salt == 0.0, axis=-1)
    return ~is_land


def test_lab_sea_hbl_ocean_columns(result_labsea):
    inputs_ds, python_ds, mitgcm_ds = result_labsea
    nt = python_ds.sizes['time']
    ocean = _ocean_mask(inputs_ds, nt)
    diff = np.abs(python_ds['hbl'].values - mitgcm_ds['hbl'].values[:nt])
    diff_ocean = diff[ocean]
    # See open issue 1DMIX-019: a small long tail of columns disagrees due to
    # bulk-Richardson threshold-crossing sensitivity (Rib landing within a
    # fraction of a percent of Ricr), not a systematic port defect. These
    # bounds reflect the full 999-timestep run's measured distribution
    # (median 0.004 m, 0.25% of columns exceed 5 m) with headroom for this
    # test's smaller 20-timestep sample.
    # 1DMIX-071 (2026-10-02): with MITgcm's tracer-point shsq/dVsq/smoothed dbloc (the replay default) the
    # 20-step sample measures median 7.3e-4 m, max 0.029 m, no column above 1 m (column-local replay:
    # median 3.4e-3 m, max 26.4 m, 2 columns above 5 m) -- the tail was a replay-input artifact. Bounds
    # tightened (were median < 0.5, fraction > 5 m < 0.02): to 0.005 and 0.001.
    # 1DMIX-080 (2026-10-03): the rest was the port's former Jerlov water type IB (MITgcm hard-codes IA,
    # swfrac.F line 92): median 7.3e-4 -> 0 m, max 0.0287 -> 2.4e-12 m (full 999 steps: median 5.4e-4 -> 0,
    # max 52.90 -> 3.6e-9 m). Median bound tightened 0.005 -> 5e-4 (the 90x40x15 convention of
    # test_kpp_mitgcm_validation_extended.py); measured 0.
    assert np.median(diff_ocean) < 5e-4, f"median hbl diff {np.median(diff_ocean):.4f} m regressed"
    assert np.mean(diff_ocean > 5.0) < 0.001, "fraction of columns exceeding the former 1DMIX-019 tail is back"


def test_lab_sea_visc_az_median(result_labsea):
    inputs_ds, python_ds, mitgcm_ds = result_labsea
    nt = python_ds.sizes['time']
    mitgcm_visc = mitgcm_ds['visc_az'].values[:nt]
    python_visc = python_ds['visc_az'].values
    active = mitgcm_visc > 1e-6
    abs_err = np.abs(python_visc[active] - mitgcm_visc[active])
    # Full run's measured median is exactly 0.0; allow headroom for sampling.
    assert np.median(abs_err) < 1e-5, f"median visc_az abs err {np.median(abs_err):.2e} regressed"
    # 1DMIX-071: p99 3.7e-5 with tracer-point inputs (1.6e-3 column-local); bound tightened from 0.01 to 1e-3.
    # 1DMIX-080 (2026-10-03, Jerlov type IA, MITgcm's hard-coded value): p99 3.8e-5 -> 0, max 6.0e-5 -> 2.3e-15;
    # bound tightened 1e-3 -> 1e-5 (this test's median convention).
    assert np.percentile(abs_err, 99) < 1e-5, f"p99 visc_az abs err {np.percentile(abs_err, 99):.2e} regressed"
