#!/bin/bash
#
# Compile and run the standalone KPPMIX driver: compiles ONLY
# MITgcm/pkg/kpp/kpp_routines.F (pristine, unmodified) plus this
# directory's kpp_standalone_main.F -- no genmake2, no full model build.
#
# Replicates MITgcm's real two-stage .F compilation (see the generated
# build's Makefile .F.o rule): `cpp -traditional -P` followed by
# tools/set64bitConst.sh, which turns MITgcm's `1. _d 0`-style literals
# into valid `1.D0` Fortran via sed -- plain `gfortran -cpp` alone does
# NOT do this substitution and would fail to compile kpp_routines.F.
#
# Usage: ./build_and_run.sh <input.txt> <output.txt>

set -e

DRIVER_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# Override with the MITGCM_ROOT environment variable on any host whose MITgcm
# checkout is not at the original macOS path (1DMIX-065: WSL uses
# ~/Projects/MITgcm). The default is unchanged.
MITGCM_ROOT="${MITGCM_ROOT:-/Users/ifenty/git_repo_others/MITgcm}"
PKGCONFIG_DIR="$MITGCM_ROOT/verification/1D_ocean_ice_column/build_docker_kppmix_extend"
CPPOPTS_DIR="$( cd "$DRIVER_DIR/../1D_ocean_ice_column/code_validation" && pwd )"

if [ $# -ne 2 ]; then
    echo "Usage: $0 <input.txt> <output.txt>"
    exit 1
fi
INPUT_TXT="$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
OUTPUT_TXT_DIR="$(cd "$(dirname "$2")" && pwd)"
OUTPUT_TXT_NAME="$(basename "$2")"

# Nr (number of vertical levels) is a SIZE.h compile-time constant, but the
# driver itself reads nrIn from input.txt at runtime and rejects a mismatch
# (kpp_standalone_main.F's "ERROR: input Nr=... does not match SIZE.h Nr=...").
# Auto-detect Nr from input.txt's first line (`ntimeIn nrIn`) and regenerate
# SIZE.h to match on every invocation -- this was previously a single
# hardcoded Nr=23 (1D_ocean_ice_column's grid), which silently required
# manual editing for any other grid size (e.g. the 50-level idealized
# scenarios). Self-correcting: no restore step needed, since this
# regenerates the same file deterministically from whatever input is used.
NR_DETECTED="$(head -1 "$INPUT_TXT" | awk '{print $2}')"
if [ -z "$NR_DETECTED" ]; then
    echo "Error: could not read Nr from first line of $INPUT_TXT"
    exit 1
fi
cat > "$DRIVER_DIR/SIZE.h" <<EOF
C     Minimal SIZE.h for the standalone KPPMIX driver.
C     Deliberately NOT the real 1D_ocean_ice_column SIZE.h (which has
C     OLx=OLy=3 for halo/exchange -- irrelevant here, since we call
C     KPPMIX directly with no tiling/exchange machinery). With OLx=OLy=0
C     and sNx=sNy=1, KPP_PARAMS.h's imt=(sNx+2*OLx)*(sNy+2*OLy) = 1: a
C     clean single-column layout, no flat-index arithmetic needed.
C     Nr is auto-regenerated by build_and_run.sh from the input file's
C     own ntimeIn/nrIn header on every run -- do not hand-edit.
      INTEGER sNx
      INTEGER sNy
      INTEGER OLx
      INTEGER OLy
      INTEGER nSx
      INTEGER nSy
      INTEGER nPx
      INTEGER nPy
      INTEGER Nx
      INTEGER Ny
      INTEGER Nr
      PARAMETER (
     &           sNx =   1,
     &           sNy =   1,
     &           OLx =   0,
     &           OLy =   0,
     &           nSx =   1,
     &           nSy =   1,
     &           nPx =   1,
     &           nPy =   1,
     &           Nx  = sNx*nSx*nPx,
     &           Ny  = sNy*nSy*nPy,
     &           Nr  =  ${NR_DETECTED})

      INTEGER MAX_OLX
      INTEGER MAX_OLY
      PARAMETER ( MAX_OLX = OLx,
     &            MAX_OLY = OLy )
EOF
echo "SIZE.h: Nr=$NR_DETECTED (auto-detected from $INPUT_TXT)"

echo "Compiling standalone KPPMIX driver..."
docker run --rm \
    -v "$MITGCM_ROOT:/mitgcm" \
    -v "$DRIVER_DIR:/driver" \
    -v "$PKGCONFIG_DIR:/pkgconfig" \
    -v "$CPPOPTS_DIR:/cppopts" \
    -v "$INPUT_TXT:/data/input.txt" \
    -v "$OUTPUT_TXT_DIR:/data/out" \
    mitgcm:latest bash -c "
    set -euo pipefail
    cd /driver
    INCS='-I/driver -I/pkgconfig -I/cppopts -I/mitgcm/pkg/kpp
          -I/mitgcm/eesupp/inc -I/mitgcm/model/inc'
    DEFINES='-DWORDLENGTH=4 -DNML_TERMINATOR -DHAVE_SYSTEM
             -DHAVE_FDATE -DHAVE_ETIME_SBR -DHAVE_CLOC -DHAVE_SETRLSTK
             -DHAVE_SIGREG -DHAVE_STAT -DHAVE_NETCDF -DHAVE_FLUSH'
    FFLAGS='-ffixed-line-length-132'

    preprocess() {
        cat \"\$1\" | cpp -traditional -P \$DEFINES \$INCS \
            | /mitgcm/tools/set64bitConst.sh > \"\$2\"
    }

    # NOTE: destination names deliberately do NOT differ from their
    # source only by case (e.g. never foo.F -> foo.f in the same dir) --
    # macOS's default case-insensitive filesystem treats those as the
    # SAME file, so a naive foo.F->foo.f pipeline races cat's read
    # against the redirect's truncate and can silently wipe the source.
    preprocess /mitgcm/pkg/kpp/kpp_routines.F kpp_routines_pp.f
    preprocess kpp_standalone_main.F kpp_standalone_main_pp.f

    gfortran \$FFLAGS -c kpp_routines_pp.f -o kpp_routines.o
    gfortran \$FFLAGS -c kpp_standalone_main_pp.f -o kpp_standalone_main.o
    gfortran kpp_routines.o kpp_standalone_main.o \
        -o kpp_standalone_main

    echo 'Build OK. Running...'
    ./kpp_standalone_main /data/input.txt /data/out/$OUTPUT_TXT_NAME
    echo 'Run complete.'
"
